version: '3.8'

services:
  retro-games-network-api:
    container_name: retro-games-network-api
    image: haoyangguo/retro-games-network-api
    ports:
      - 8088:8088
    networks:
      - retro-games-network-backend
    depends_on:
      - postgres

  postgres:
    container_name: retro-games-network-postgresql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: retro_games_network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - retro-games-network-backend
    restart: unless-stopped

networks:
  retro-games-network-backend:
    driver: bridge

volumes:
  postgres:
    driver: local
